# Generated by Django 4.2.7 on 2024-01-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_forumpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='blog.category'),
        ),
    ]
