# Generated by Django 4.2.7 on 2024-01-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_subject_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
